import type { Metadata } from "next";

import "./globals.scss";
import "./styles.scss";
import { pretendard } from "@font";
import { ModalContextProvider } from "@contexts/ModalContext";

export const metadata: Metadata = {
  title: "강혜진 | Frontend Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={pretendard.variable}>
      <body>
        <ModalContextProvider>{children}</ModalContextProvider>
      </body>
    </html>
  );
}
